name = "JuXIMC"
uuid = "88c757fa-87cc-459a-a7bb-a68242c6a82c"
authors = ["bergermann <dominik.bergermann@rwth-aachen.de> and contributors"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
